import { ReasoningContext } from "@/engines/reasoning";
import {
  PlanningResult,
    PlanningStep,
    } from "./PlanningTypes";

    export class PlanningEngine {

      public execute(
          context: ReasoningContext
            ): ReasoningContext {

                context.plan = this.createPlan(
                      context.message
                          );

                              return context;
                                }

                                  public createPlan(
                                      message: string
                                        ): PlanningResult {

                                            const steps = this.buildPlan(message);

                                                return {
                                                      steps,
                                                            confidence: 0.95,
                                                                };
                                                                  }

                                                                    private buildPlan(
                                                                        message: string
                                                                          ): PlanningStep[] {

                                                                              const text = message.toLowerCase();

                                                                                  if (
                                                                                        text.includes("build") ||
                                                                                              text.includes("project") ||
                                                                                                    text.includes("system")
                                                                                                        ) {
                                                                                                              return [
                                                                                                                      {
                                                                                                                                id: 1,
                                                                                                                                          title: "Understand requirements",
                                                                                                                                                    completed: false,
                                                                                                                                                            },
                                                                                                                                                                    {
                                                                                                                                                                              id: 2,
                                                                                                                                                                                        title: "Design the solution",
                                                                                                                                                                                                  completed: false,
                                                                                                                                                                                                          },
                                                                                                                                                                                                                  {
                                                                                                                                                                                                                            id: 3,
                                                                                                                                                                                                                                      title: "Break into tasks",
                                                                                                                                                                                                                                                completed: false,
                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                          id: 4,
                                                                                                                                                                                                                                                                                    title: "Implement the solution",
                                                                                                                                                                                                                                                                                              completed: false,
                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                        id: 5,
                                                                                                                                                                                                                                                                                                                                  title: "Review and improve",
                                                                                                                                                                                                                                                                                                                                            completed: false,
                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                          ];
                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                  if (
                                                                                                                                                                                                                                                                                                                                                                        text.includes("plan") ||
                                                                                                                                                                                                                                                                                                                                                                              text.includes("roadmap")
                                                                                                                                                                                                                                                                                                                                                                                  ) {
                                                                                                                                                                                                                                                                                                                                                                                        return [
                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                          id: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                    title: "Define objective",
                                                                                                                                                                                                                                                                                                                                                                                                                              completed: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        id: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title: "Create roadmap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            completed: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: "Prioritize tasks",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completed: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: "Execute plan",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        completed: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: "Understand request",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            completed: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: "Generate response",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                completed: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const planningEngine = new PlanningEngine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default planningEngine;