import { MemoryRecord } from "./MemoryTypes";

export interface MemorySummary {
    summary: string;
        keyFacts: string[];
            keyGoals: string[];
                keyEvents: string[];
                    keyPreferences: string[];
                    }

                    export class MemorySummarizer {

                        /**
                             * Summarize a collection of memories.
                                  */
                                      public async summarize(
                                              memories: MemoryRecord[]
                                                  ): Promise<MemorySummary> {

                                                          const keyFacts: string[] = [];
                                                                  const keyGoals: string[] = [];
                                                                          const keyEvents: string[] = [];
                                                                                  const keyPreferences: string[] = [];

                                                                                          for (const memory of memories) {

                                                                                                      switch (memory.type) {

                                                                                                                      case "fact":
                                                                                                                                          keyFacts.push(memory.content);
                                                                                                                                                              break;

                                                                                                                                                                              case "goal":
                                                                                                                                                                                                  keyGoals.push(memory.content);
                                                                                                                                                                                                                      break;

                                                                                                                                                                                                                                      case "event":
                                                                                                                                                                                                                                                          keyEvents.push(memory.content);
                                                                                                                                                                                                                                                                              break;

                                                                                                                                                                                                                                                                                              case "preference":
                                                                                                                                                                                                                                                                                                                  keyPreferences.push(memory.content);
                                                                                                                                                                                                                                                                                                                                      break;

                                                                                                                                                                                                                                                                                                                                                      default:
                                                                                                                                                                                                                                                                                                                                                                          break;

                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                      const summary = [
                                                                                                                                                                                                                                                                                                                                                                                                                  ...keyFacts,
                                                                                                                                                                                                                                                                                                                                                                                                                              ...keyGoals,
                                                                                                                                                                                                                                                                                                                                                                                                                                          ...keyEvents,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...keyPreferences
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ].join(" ");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  summary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              keyFacts,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keyGoals,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      keyEvents,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  keyPreferences
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * Summarize a single memory.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public async summarizeMemory(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        memory: MemoryRecord
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ): Promise<string> {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return `${memory.title}: ${memory.content}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const memorySummarizer = new MemorySummarizer();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default memorySummarizer;