import { MemoryRecord } from "./MemoryTypes";

export class MemoryScorer {

    /**
         * Calculate a relevance score for a memory.
              */
                  public score(
                          memory: MemoryRecord,
                                  query?: string
                                      ): number {

                                              let score = 0;

                                                      // Importance
                                                              score += memory.metadata.importance * 5;

                                                                      // Confidence
                                                                              score += memory.metadata.confidence * 3;

                                                                                      // Access frequency
                                                                                              score += memory.metadata.accessCount;

                                                                                                      // Recent memories are more valuable
                                                                                                              const age =
                                                                                                                          Date.now() -
                                                                                                                                      memory.metadata.updatedAt.getTime();

                                                                                                                                              const days =
                                                                                                                                                          age / (1000 * 60 * 60 * 24);

                                                                                                                                                                  if (days < 1) {

                                                                                                                                                                              score += 25;

                                                                                                                                                                                      } else if (days < 7) {

                                                                                                                                                                                                  score += 15;

                                                                                                                                                                                                          } else if (days < 30) {

                                                                                                                                                                                                                      score += 5;

                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                      // Query matching
                                                                                                                                                                                                                                              if (query) {

                                                                                                                                                                                                                                                          const search = query.toLowerCase();

                                                                                                                                                                                                                                                                      if (
                                                                                                                                                                                                                                                                                      memory.title
                                                                                                                                                                                                                                                                                                          .toLowerCase()
                                                                                                                                                                                                                                                                                                                              .includes(search)
                                                                                                                                                                                                                                                                                                                                          ) {
                                                                                                                                                                                                                                                                                                                                                          score += 50;
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                  if (
                                                                                                                                                                                                                                                                                                                                                                                                  memory.content
                                                                                                                                                                                                                                                                                                                                                                                                                      .toLowerCase()
                                                                                                                                                                                                                                                                                                                                                                                                                                          .includes(search)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      score += 30;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              memory.metadata.tags.some(tag =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tag.toLowerCase().includes(search)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              score += 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return score;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const memoryScorer = new MemoryScorer();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default memoryScorer;